import type { ImageReplaceVoiceData } from '../ChatPortraitModels';
import CONSTANTS from '../constants';

export default {
  SYSTEM_ID: 'a5e',
  imageReplacerDamageType: <ImageReplaceVoiceData[]>[
    { name: 'A5E.DamageAcid', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/acid.svg` },
    { name: 'A5E.DamageBludgeoning', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/bludgeoning.svg` },
    { name: 'A5E.DamageCold', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/cold.svg` },
    { name: 'A5E.DamageFire', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/fire.svg` },
    { name: 'A5E.DamageForce', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/force.svg` },
    { name: 'A5E.DamageLightning', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/lightning.svg` },
    { name: 'A5E.DamageNecrotic', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/necrotic.svg` },
    { name: 'A5E.DamagePiercing', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/piercing.svg` },
    { name: 'A5E.DamagePoison', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/poison.svg` },
    { name: 'A5E.DamagePsychic', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/psychic.svg` },
    { name: 'A5E.DamageRadiant', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/radiant.svg` },
    { name: 'A5E.DamageSlashing', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/slashing.svg` },
    { name: 'A5E.DamageThunder', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/thunder.svg` },
    { name: 'A5E.DamageUnknown', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/non_magical_physical.svg` },
  ],
  imageReplacerWeaponProperties: <ImageReplaceVoiceData[]>[
    { name: 'A5E.WeaponPropertyBurn', icon: `` },
    { name: 'A5E.WeaponPropertyBreaker', icon: `` },
    { name: 'A5E.WeaponPropertyCompounding', icon: `` },
    { name: 'A5E.WeaponPropertyDefensive', icon: `` },
    { name: 'A5E.WeaponPropertyDualWielding', icon: `` },
    { name: 'A5E.WeaponPropertyFinesse', icon: `` },
    { name: 'A5E.WeaponPropertyFlamboyant', icon: `` },
    { name: 'A5E.WeaponPropertyHandMounted', icon: `` },
    { name: 'A5E.WeaponPropertyHeavy', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/heavy.svg` },
    { name: 'A5E.WeaponPropertyInaccurate', icon: `` },
    { name: 'A5E.WeaponPropertyLoading', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/loading.svg` },
    { name: 'A5E.WeaponPropertyMounted', icon: `` },
    { name: 'A5E.WeaponPropertyMuzzleLoading', icon: `` },
    { name: 'A5E.WeaponPropertyParrying', icon: `` },
    { name: 'A5E.WeaponPropertyParryingImmunity', icon: `` },
    { name: 'A5E.WeaponPropertyQuickdraw', icon: `` },
    { name: 'A5E.WeaponPropertyRange', icon: `` },
    { name: 'A5E.WeaponPropertyReach', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/reach.svg` },
    { name: 'A5E.WeaponPropertyRifled', icon: `` },
    { name: 'A5E.WeaponPropertyScatter', icon: `` },
    { name: 'A5E.WeaponPropertyShock', icon: `` },
    { name: 'A5E.WeaponPropertySimple', icon: `` },
    { name: 'A5E.WeaponPropertyThrown', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/thrown.svg` },
    { name: 'A5E.WeaponPropertyTriggerCharge', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/special.svg` },
    { name: 'A5E.WeaponPropertyTrip', icon: `` },
    { name: 'A5E.WeaponPropertyTwoHanded', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/two-Handed.svg` },
    { name: 'A5E.WeaponPropertyVersatile', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/versatile.svg` },
    { name: 'A5E.WeaponPropertyVicious', icon: `` },
  ],
  imageReplacerIconizer: <ImageReplaceVoiceData[]>[
    { name: 'A5E.AbilityDefault', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/gaming_set.svg` },
    { name: 'A5E.AbilitySpellcasting', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/arcana.svg` },
    { name: 'A5E.AbilityCheck', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/survival.svg` },

    { name: 'A5E.AbilityStr', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/strength.svg` },
    { name: 'A5E.AbilityDex', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/dexterity.svg` },
    { name: 'A5E.AbilityCon', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/constitution.svg` },
    { name: 'A5E.AbilityInt', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/intelligence.svg` },
    { name: 'A5E.AbilityWis', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/wisdom.svg` },
    { name: 'A5E.AbilityCha', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/charisma.svg` },

    { name: 'SkillAcr', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/acrobatics.svg` },
    { name: 'SkillAni', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/animal_handling.svg` },
    { name: 'SkillArc', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/arcana.svg` },
    { name: 'SkillAth', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/athletics.svg` },
    { name: 'SkillCul', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/culture.svg` },
    { name: 'SkillDec', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/deception.svg` },
    { name: 'SkillEng', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/engineering.svg` },
    { name: 'SkillHis', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/history.svg` },
    { name: 'SkillIns', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/insight.svg` },
    { name: 'SkillItm', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/intimidation.svg` },
    { name: 'SkillInv', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/investigation.svg` },
    { name: 'SkillMed', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/medicine.svg` },
    { name: 'SkillNat', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/nature.svg` },
    { name: 'SkillPrc', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/perception.svg` },
    { name: 'SkillPrf', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/performance.svg` },
    { name: 'SkillPer', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/persuasion.svg` },
    { name: 'SkillRel', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/religion.svg` },
    { name: 'SkillSlt', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/sleight_of_hand.svg` },
    { name: 'SkillSte', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/stealth.svg` },
    { name: 'SkillSur', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/survival.svg` },
    { name: 'SkillSpecialties', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/specialties.svg` },
    { name: 'SkillSpecialtyAberrations', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/aberrations.svg` },
    { name: 'SkillSpecialtyActing', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/acting.svg` },
    { name: 'SkillSpecialtyAppraisal', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/appraisal.svg` },
    { name: 'SkillSpecialtyAlignment', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/alignment.svg` },
    { name: 'SkillSpecialtyAnimals', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/animals.svg` },
    { name: 'SkillSpecialtyAnonymity', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/anonymity.svg` },
    { name: 'SkillSpecialtyArchitecture', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/architecture.svg` },
    { name: 'SkillSpecialtyArts', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/arts.svg` },
    { name: 'SkillSpecialtyAstronomy', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/astronomy.svg` },
    { name: 'SkillSpecialtyAuthority', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/authority.svg` },
    { name: 'SkillSpecialtyAutopsy', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/autopsy.svg` },
    { name: 'SkillSpecialtyBalancing', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/balancing.svg` },
    { name: 'SkillSpecialtyBeastLore', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/beast Lore.svg` },
    { name: 'SkillSpecialtyBoasting', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/boasting.svg` },
    { name: 'SkillSpecialtyBribery', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/bribery.svg` },
    { name: 'SkillSpecialtyCalming', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/calming.svg` },
    { name: 'SkillSpecialtyCelestials', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/celestials.svg` },
    { name: 'SkillSpecialtyCamouflage', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/camouflage.svg` },
    { name: 'SkillSpecialtyCasing', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/casing.svg` },
    { name: 'SkillSpecialtyChemistry', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/chemistry.svg` },
    { name: 'SkillSpecialtyCiphers', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/ciphers.svg` },
    { name: 'SkillSpecialtyClimbing', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/climbing.svg` },
    {
      name: 'SkillSpecialtyConcealingEmotions',
      icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/concealing_emotions.svg`,
    },
    { name: 'SkillSpecialtyComposing', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/composing.svg` },
    { name: 'SkillSpecialtyConstructs', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/constructs.svg` },
    { name: 'SkillSpecialtyCourtlyManners', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/courtly_manners.svg` },
    { name: 'SkillSpecialtyCults', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/cults.svg` },
    { name: 'SkillSpecialtyDancing', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/dancing.svg` },
    { name: 'SkillSpecialtyDeciphering', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/deciphering.svg` },
    { name: 'SkillSpecialtyDetectingLies', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/detecting_lies.svg` },
    { name: 'SkillSpecialtyDetection', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/detection.svg` },
    { name: 'SkillSpecialtyDiseases', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/diseases.svg` },
    { name: 'SkillSpecialtyDistraction', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/distraction.svg` },
    { name: 'SkillSpecialtyDragons', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/dragons.svg` },
    { name: 'SkillSpecialtyDriving', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/driving.svg` },
    { name: 'SkillSpecialtyDungeoneering', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/dungeoneering.svg` },
    { name: 'SkillSpecialtyElementals', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/elementals.svg` },
    { name: 'SkillSpecialtyEmpires', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/empires.svg` },
    { name: 'SkillSpecialtyEscapeArtistry', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/escape_artistry.svg` },
    { name: 'SkillSpecialtyEtiquette', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/etiquette.svg` },
    { name: 'SkillSpecialtyExplosives', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/explosives.svg` },
    { name: 'SkillSpecialtyFarming', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/farming.svg` },
    { name: 'SkillSpecialtyFarsight', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/farsight.svg` },
    { name: 'SkillSpecialtyFerocity', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/ferocity.svg` },
    { name: 'SkillSpecialtyFey', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/fey.svg` },
    { name: 'SkillSpecialtyFineArt', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/fine_art.svg` },
    { name: 'SkillSpecialtyFlattery', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/flattery.svg` },
    { name: 'SkillSpecialtyForaging', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/foraging.svg` },
    {
      name: 'SkillSpecialtyForbiddenKnowledge',
      icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/forbidden_knowledge.svg`,
    },
    { name: 'SkillSpecialtyForensics', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/forensics.svg` },
    { name: 'SkillSpecialtyFiends', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/fiends.svg` },
    { name: 'SkillSpecialtyGadgetry', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/gadgetry.svg` },
    { name: 'SkillSpecialtyGatheringRumors', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/gathering_rumors.svg` },
    { name: 'SkillSpecialtyGenealogy', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/genealogy.svg` },
    { name: 'SkillSpecialtyGods', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/gods.svg` },
    { name: 'SkillSpecialtyHerbalism', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/herbalism.svg` },
    { name: 'SkillSpecialtyHolySymbols', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/holy_symbols.svg` },
    { name: 'SkillSpecialtyHunting', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/hunting.svg` },
    { name: 'SkillSpecialtyInterrogation', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/interrogation.svg` },
    { name: 'SkillSpecialtyInvisibleObjects', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/invisible _objects.svg` },
    { name: 'SkillSpecialtyJumping', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/jumping.svg` },
    { name: 'SkillSpecialtyLaws', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/laws.svg` },
    { name: 'SkillSpecialtyLeadership', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/leadership.svg` },
    { name: 'SkillSpecialtyLegends', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/legends.svg` },
    { name: 'SkillSpecialtyLegerdemain', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/legerdemain.svg` },
    { name: 'SkillSpecialtyLifting', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/lifting.svg` },
    { name: 'SkillSpecialtyLinguistics', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/linguistics.svg` },
    { name: 'SkillSpecialtyListening', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/listening.svg` },
    { name: 'SkillSpecialtyMathematics', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/mathematics.svg` },
    { name: 'SkillSpecialtyMechanicalTraps', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/mechanical_traps.svg` },
    { name: 'SkillSpecialtyMimicry', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/mimicry.svg` },
    { name: 'SkillSpecialtyMonstrosities', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/monstrosities.svg` },
    { name: 'SkillSpecialtyMorality', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/morality.svg` },
    { name: 'SkillSpecialtyNegotiation', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/negotiation.svg` },
    { name: 'SkillSpecialtyOozes', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/oozes.svg` },
    { name: 'SkillSpecialtyPeacemaking', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/peacemaking.svg` },
    { name: 'SkillSpecialtyPickpocketing', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/pickpocketing.svg` },
    { name: 'SkillSpecialtyThePlanes', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/the_planes.svg` },
    { name: 'SkillSpecialtyPlantLore', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/plant_lore.svg` },
    { name: 'SkillSpecialtyPoisons', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/poisons.svg` },
    { name: 'SkillSpecialtyProphecy', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/prophecy.svg` },
    { name: 'SkillSpecialtyReadingEmotions', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/reading_emotions.svg` },
    { name: 'SkillSpecialtyRegionalGoods', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/regional_goods.svg` },
    { name: 'SkillSpecialtyResearch', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/research.svg` },
    { name: 'SkillSpecialtyRiding', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/riding.svg` },
    { name: 'SkillSpecialtyRunning', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/running.svg` },
    { name: 'SkillSpecialtyScent', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/scent.svg` },
    { name: 'SkillSpecialtySensingMotives', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/sensing_motives.svg` },
    { name: 'SkillSpecialtySiegecraft', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/siegecraft.svg` },
    { name: 'SkillSpecialtySinging', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/singing.svg` },
    { name: 'SkillSpecialtySpeaking', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/speaking.svg` },
    { name: 'SkillSpecialtyStreetwise', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/streetwise.svg` },
    { name: 'SkillSpecialtySubtleThreats', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/subtle_threats.svg` },
    { name: 'SkillSpecialtySwimming', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/swimming.svg` },
    { name: 'SkillSpecialtySwinging', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/swinging.svg` },
    { name: 'SkillSpecialtyThrowing', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/throwing.svg` },
    { name: 'SkillSpecialtyTracking', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/tracking.svg` },
    { name: 'SkillSpecialtyTrade', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/trade.svg` },
    { name: 'SkillSpecialtyTraining', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/training.svg` },
    { name: 'SkillSpecialtyTrapfinding', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/trapfinding.svg` },
    { name: 'SkillSpecialtyTumbling', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/tumbling.svg` },
    { name: 'SkillSpecialtyUndead', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/undead.svg` },
    { name: 'SkillSpecialtyWars', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/wars.svg` },
    { name: 'SkillSpecialtyWayfinding', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/wayfinding.svg` },
    { name: 'SkillSpecialtyWeaponDisplays', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/weapon_displays.svg` },
    { name: 'SkillSpecialtyWeather', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/weather.svg` },
    { name: 'SkillSpecialtyWriting', icon: `/modules/${CONSTANTS.MODULE_NAME}/assets/writing.svg` },
  ],
};
