export interface ChatPortraitSettings{
    useTokenImage: boolean,
    portraitSize: number,
    portraitSizeItem: number,
    borderShape: string,
    useUserColorAsBorderColor: boolean,
    borderColor: string,
    borderWidth: number,
    useUserColorAsChatBackgroundColor: boolean,
    useUserColorAsChatBorderColor: boolean,
    flavorNextToPortrait: boolean,
    forceNameSearch: boolean,
    hoverTooltip: boolean,
    textSizeName: number,
    displaySetting: string,
    useAvatarImage: boolean,
    displayUnknown: string,
}
